; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
; Projektspezifische Einstellungen:
; Ausgabegeschwindigkeit für den serial Monitor
monitor_speed = 115200
; COM-Port, an dem der ESP32 angeschlossen wird
upload_port = COM4
; Libs aus PlatformIO & GitHub
lib_deps =
    paulstoffregen/OneWire@2.3.7  ; v2.3.8 hat einen bug in 2 Zeilen, daher v2.3.7 - Patch im master schon eingebaut aber noch nicht released
    milesburton/DallasTemperature@^4.0.4
    knolleary/PubSubClient@^2.8
